version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - lab_11
    privileged: true
    user: root
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /usr/bin/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/jenkins:/var/jenkins_home
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    networks: 
      - lab_11
    ports:
      - "9000:9000"
  registry:
    image: registry
    container_name: registry
    networks:
      - lab_11
    ports:
      - "5000:5000"
    volumes:
      - /var/lib/registry:/var/lib/registry
networks:
  lab_11:
